### ISSUE TITLE
Can pydictor find and remove non-UTF-8 characters?

### ISSUE THREAD

**Issue by Privacy6484847** [LandGrey/pydictor#34]
Can pydictor find and remove non-UTF-8 characters?

**Comment by LandGrey** [comment]
> Can pydictor find and remove non-UTF-8 characters?

Currently not contains this function, you can use other tool to finish it, such as `iconv`

**Comment by Privacy6484847** [comment]
Thanks for answer. 
I applied the `iconv` tool with this command  `iconv -f utf-8 -t utf-8 -c test.txt -o clean_test.txt`. 
Then i used pydictor on the clean_test.txt with: `pydictor --len 6 20 -tool handler clean_test.txt -o super_clean_test.txt`

But i got the following error:
`  File "E:\pydictor-2.0.5\pydictor.py", line 107, in <module>
    tool_parser()
  File "E:\pydictor-2.0.5\lib\parse\argsparse.py", line 104, in tool_parser
    get_handler_dic(pyoptions.args_tool[1])
  File "E:\pydictor-2.0.5\tools\handler.py", line 24, in get_handler_dic
    for item in f.readlines():
  File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3858: character maps to <undefined>`

**Comment by Privacy6484847** [comment]
Thanks for answer.

 I applied the iconv tool with this command iconv -f utf-8 -t utf-8 -c test.txt -o clean_test.txt.
Then i used pydictor on the clean_test.txt with: pydictor --len 6 20 -tool handler clean_test.txt -o super_clean_test.txt

But i got the following error:


```
File "E:\pydictor-2.0.5\pydictor.py", line 107, in <module> tool_parser() 
File "E:\pydictor-2.0.5\lib\parse\argsparse.py", line 104, in tool_parser get_handler_dic(pyoptions.args_tool[1]) 
File "E:\pydictor-2.0.5\tools\handler.py", line 24, in get_handler_dic for item in f.readlines(): 
File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0]
 UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3858: character maps to <undefined>
```

**Comment by LandGrey** [comment]
> Thanks for answer.
> 
> I applied the iconv tool with this command iconv -f utf-8 -t utf-8 -c test.txt -o clean_test.txt. Then i used pydictor on the clean_test.txt with: pydictor --len 6 20 -tool handler clean_test.txt -o super_clean_test.txt
> 
> But i got the following error:
> 
> ```
> File "E:\pydictor-2.0.5\pydictor.py", line 107, in <module> tool_parser() 
> File "E:\pydictor-2.0.5\lib\parse\argsparse.py", line 104, in tool_parser get_handler_dic(pyoptions.args_tool[1]) 
> File "E:\pydictor-2.0.5\tools\handler.py", line 24, in get_handler_dic for item in f.readlines(): 
> File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>  UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3858: character maps to <undefined>
> ```

I add the filter printable character tool for pydictor just now.
you can download the latest pydictor version (2.1.5.6) and using command  `python pydictor.py --len 6 20 -tool printabler test.txt ` to get your wordlist.

**Comment by Privacy6484847** [comment]
Thank you for your help. 
Unfortunately the issue is still occuring. You can test it with this file i found online: [https://www.w3.org/2001/06/utf-8-wrong/UTF-8-test.html](url)

**Comment by LandGrey** [comment]
> [https://www.w3.org/2001/06/utf-8-wrong/UTF-8-test.html](url)

I download the `UTF-8-test.html` page and testing is ok.

<img width="867" alt="1" src="https://user-images.githubusercontent.com/16769779/149259350-ed453531-7533-4378-a557-7ef1abbf0eb3.png">

**Comment by LandGrey** [comment]
> Thank you for your help. Unfortunately the issue is still occuring. You can test it with this file i found online: [https://www.w3.org/2001/06/utf-8-wrong/UTF-8-test.html](url)

I fixed the bug.
Please download pydictor `2.1.5.7` version and using command ` python pydictor.py --len 6 20 -tool printabler test.txt`.

**Comment by Privacy6484847** [comment]
Thank you for your effort.
Unfortunately i got the same error. 

![Untitled](https://user-images.githubusercontent.com/88597193/149263500-841035ae-6bba-4aba-b3f5-713135009fe9.jpg)

**Comment by LandGrey** [comment]
> 2.1.5.7

try `2.1.5.8` version.

**Comment by Privacy6484847** [comment]
Unfortunately still the same error. Maybe it's an issue related to Python itself. When googling it seems that alot of people are dealing with encoding issues on Python.

![image](https://user-images.githubusercontent.com/88597193/149370266-43977fc6-9899-463d-a24a-8446b3cfc190.png)

**Comment by Privacy6484847** [comment]
You did it! Amazing!!
Thank you so so much!! 💯

![image](https://user-images.githubusercontent.com/88597193/149386263-106082e8-240a-4519-9dd2-a251bb36eff8.png)

**Comment by Privacy6484847** [comment]
Update: Now the pydictor works well with non UTF-8 characters.
The issue i got now is that i hit a memory limit.

![image](https://user-images.githubusercontent.com/88597193/149410639-5a6d30a6-353e-4cf7-bf34-711257b70e05.png)

**Comment by LandGrey** [comment]
> Update: Now the pydictor works well with non UTF-8 characters. The issue i got now is that i hit a memory limit.
> 
> ![image](https://user-images.githubusercontent.com/88597193/149410639-5a6d30a6-353e-4cf7-bf34-711257b70e05.png)

try latest version `2.1.6.0`.

**Comment by Privacy6484847** [comment]
I tried the `2.1.6.0` version and i got a different behavior. But the same end result.
The Memory behavior changed. Instead of a steight shoot up i got a slower and steady rise for 5 min then it eventually gave the memory error.

During the process:

![image](https://user-images.githubusercontent.com/88597193/149600722-bc68eed8-3420-46b5-8d32-99a76c1c19e5.png)

At the end of the process:

![image](https://user-images.githubusercontent.com/88597193/149600643-8d25dcc7-20af-40b2-8ba9-1cc7828ab4ff.png)

![image](https://user-images.githubusercontent.com/88597193/149600660-d3bc3e4e-181b-45c4-8b46-fed411d56272.png)

**Comment by LandGrey** [comment]
> I tried the `2.1.6.0` version and i got a different behavior. But the same end result. The Memory behavior changed. Instead of a straight shoot up i got a slower and steady rise for 5 min then it eventually gave the memory error.
> 
> During the process:
> 
> ![image](https://user-images.githubusercontent.com/88597193/149600722-bc68eed8-3420-46b5-8d32-99a76c1c19e5.png)
> 
> At the end of the process:
> 
> ![image](https://user-images.githubusercontent.com/88597193/149600643-8d25dcc7-20af-40b2-8ba9-1cc7828ab4ff.png)
> 
> ![image](https://user-images.githubusercontent.com/88597193/149600660-d3bc3e4e-181b-45c4-8b46-fed411d56272.png)

That's due to "memory remove duplicate file lines by preserving order" caused.
Your input files must be huge, I would to consider a better way to fix it.

**Comment by LandGrey** [comment]
> I tried the `2.1.6.0` version and i got a different behavior. But the same end result. The Memory behavior changed. Instead of a straight shoot up i got a slower and steady rise for 5 min then it eventually gave the memory error.
> 
> During the process:
> 
> ![image](https://user-images.githubusercontent.com/88597193/149600722-bc68eed8-3420-46b5-8d32-99a76c1c19e5.png)
> 
> At the end of the process:
> 
> ![image](https://user-images.githubusercontent.com/88597193/149600643-8d25dcc7-20af-40b2-8ba9-1cc7828ab4ff.png)
> 
> ![image](https://user-images.githubusercontent.com/88597193/149600660-d3bc3e4e-181b-45c4-8b46-fed411d56272.png)

maybe you can try version `2.1.7.0`.

**Comment by Privacy6484847** [comment]
Unfortunately the same behavior. For info the file size of this dictionnary is 400GB. 

![image](https://user-images.githubusercontent.com/88597193/150025052-eb8ea3bd-b8f8-4ea4-b3dd-28d7f4569606.png)

![image](https://user-images.githubusercontent.com/88597193/150025388-2316a626-4429-496e-9908-385ad21dde33.png)

**Comment by LandGrey** [comment]
> 

Download the latest version `2.1.7.1`, I reduce the pydictor `lib/data/data.py` file `pyoptions.memory_unique_max_lines_count` variable to `10000000 `, just try again. 
If the same behavior, you can reduce the variable and try it again.

**Comment by LandGrey** [comment]
> > 
> 
> Download the latest version `2.1.7.1`, I reduce the pydictor `lib/data/data.py` file `pyoptions.memory_unique_max_lines_count` variable to `10000000 `, just try again. If the same behavior, you can reduce the variable and try it again.



> Unfortunately the same behavior. For info the file size of this dictionnary is 400GB.
> 
> ![image](https://user-images.githubusercontent.com/88597193/150025052-eb8ea3bd-b8f8-4ea4-b3dd-28d7f4569606.png)
> 
> ![image](https://user-images.githubusercontent.com/88597193/150025388-2316a626-4429-496e-9908-385ad21dde33.png)

Download the latest version `2.1.7.1`, I reduce the pydictor `lib/data/data.py` file `pyoptions.memory_unique_max_lines_count` variable to `10000000 `, just try again. 
If the same behavior, you can reduce the variable and try it again.

**Comment by Privacy6484847** [comment]
OK. I'm experimenting playing with the variables. I would like to ask you if there is a way for pydictor to show the progress in %, or in lines processed. Any indication of the progress made by Pydictor would be very helpful for troubleshooting and also benchmarking the performance effect of different variables :)

**Comment by Privacy6484847** [comment]
So after a lot of testing. Reducing this variable `pyoptions.memory_unique_max_lines_count` lowers performance dramatically and it just makes the error take more time to happen.
I actually even tried with a relatively small file of 30gb. And i gave windows 60GB of paging file size. Still Pydictor ended up in memory error.
Maybe instead of using the paging file, pydictor should save incrementally the data processed directly to the hard drive. :)

**Comment by tl123987** [comment]
可以加个限制字典生成行数的功能不

**Comment by tl123987** [comment]
![image](https://user-images.githubusercontent.com/65206700/154453376-6adaaad2-df81-4957-bdc0-9c035b192801.png)

**Comment by tl123987** [comment]
> ![图像](https://user-images.githubusercontent.com/65206700/154453376-6adaaad2-df81-4957-bdc0-9c035b192801.png)

自己写规则出现错误咋回事哇，作者
